### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by WSMorrison** [WSMorrison/BricksThenMadeNow#47]
Create a comprehensive Readme.

- [ ] Header with brief explanation
  - [ ] Responsive view of front page
  - [ ] Link to deployed site
  - [ ] Link to GitHub 
- [ ] Contents
- [ ] User Experience
  - [ ] User Stories
- [ ] Design
  - [ ] #40 
  - [ ] #39
  - [ ] Images 
- [ ] Planning
  - [ ] #41 
  - [ ] #34 
  - [ ] #35 
  - [ ] Agile Technology
- [ ]  SEO
  - [ ] #33 
  - [ ] #36 
  - [ ] #37 
  - [ ] #26 
  - [ ] #27 
- [ ] Features
  - [ ] General features of All Pages
  - [ ] Features of Individual Pages
  - [ ] Defensive design
  - [ ] Accessibilty
  - [ ] Future Implementations
- [ ] Technologies Used
  - [ ] Languages Used
  - [ ] Frameworkes, Libraries, Programs Used
- [ ] # Local Development
- [ ] # Testing
- [ ] Credits
  - [ ] Code Used
  - [ ] Media
